version: '3.7'

services:
  django_app:
    build:
      context: .
    container_name: weather_app
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:10-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  redis:
    image: "redis:alpine"
    container_name: redis_cache
    ports:
      - '6379:6379'
volumes:
  static:
  postgres_data: